name: terraform-plan
on: 
  workflow_dispatch:
  pull_request:
    paths:
      - '*.tf'
      - '**/*.tf'

# permissions:
#   pull-requests: write
#   id-token: write
#   contents: read
jobs:
  terraform-plan:
    uses: ./.github/workflows/reusable_plan.yml
    with:
      oidc-role-arn: arn:aws:iam::169421194568:role/githubOIDCAssumeRole